version: '3.3'
services:
    db:
      image: mysql
      restart: always
      env_file:
          - .env
      environment:
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      volumes:
          - ../../opt/gogs/mysql:/var/lib/mysql
    app:
      image: gogs/gogs
      restart: always
      ports:
        - ${GOGS_SSH_PORT}:22
        - ${GOGS_HOST_PORT}:3000
      environment:
        - RUN_CROND=true
      volumes:
        - ../../opt/gogs/data:/data
      depends_on:
        - db

# volumes:
#   app-data:
#     driver: local
#   db-data:
#     driver: local