version: "3"
services:
  web:
    image: gogs/gogs
    restart: always
    volumes:
      - ../../opt/gogs/data:/data
    ports:
      - "10080:3000" 
  db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 20080:8080