version: "2.0"
services:
  jenkins:
    image: "jenkins/jenkins:lts"
    ports:
     - "8088:8080"
     - "50005:50000"
    volumes:
     - "~/Documents/Proyectos/ProjectsDocker/ic/jenkins_home:/var/jenkins_home"
  artifactory:
    image: "docker.bintray.io/jfrog/artifactory-oss"
    ports: 
      - "8089:8081"   


