version: "2.0"
services:
  test-node:
    build: .
    command: sh -c 'npm install; npm start'
    ports:
      - '3002:3000'
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - ./test-login-2:/app
  mongo:
    image: "mongo:latest"
    ports: 
      - "27017:27017"
    volumes: 
      - /data/db:/data/db
    command: mongod --smallfiles     
