version: "3"
services:
  web:
    image: gogs/gogs
    restart: always
    volumes:
      - ../../opt/gogs/data:/data
    ports:
      - "10080:3000" 
  db:
    image: mysql
    restart: always
    volumes:
      - ../../opt/gogs/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
